version: 0.2

env:
  variables:
    NODE_ENV: "${env}"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Install backup
      # - npm run lint
  pre_build:
    commands:
      - Echo Pre-Build backup
  build:
    commands:
      - echo Build backup

artifacts:
  files:
    - "**/*"
  name: "web-dist-${env}"
  base-directory: build

cache:
  paths:
    - /root/.npm/**/*